#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo " 🐾 Running husky [commit-msg] hooks "
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo "👀 See all the rules of commit messages in 'commit.config.js' file"

npx --no -- commitlint --edit "\${1}"
