#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo " 🐾 Running husky [pre-commit] hooks "
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo "👀 See the configurations for lint-staged in 'lint-staged.config.js' file"

yarn precommit
