#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo " 🐾 Running husky [pre-push] hooks "
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo "📦 Trying to buld the project befor pushing to github"

yarn build
